# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dNV4LXvFWpKH7Gt6hgROn3KAo2cpHETA
"""

import random

def simulador_cuantico_simple():
   
    # 1. CODIFICACIÓN
    # Imaginamos que queremos enviar un '0' lógico (|000>)
    # En la realidad esto son amplitudes de probabilidad, aquí simulamos los bits
    qubits = [0, 0, 0]
    print(f"\n1. Estado Inicial Codificado: |{qubits[0]}{qubits[1]}{qubits[2]}>")

    # 2. INTRODUCCIÓN DE ERROR (RUÍDO)
    print("\n--- INTRODUCIENDO RUIDO ---")
    print("Opciones: 0 (Sin error), 1 (Error Q1), 2 (Error Q2), 3 (Error Q3)")
    opcion = input("¿Dónde quieres el error? Escribe el número: ")

    if opcion == '1':
        qubits[0] = 1 - qubits[0] # Cambia 0 a 1 (Bit Flip)
        print(">> ¡Error tipo X aplicado en Qubit 1!")
    elif opcion == '2':
        qubits[1] = 1 - qubits[1]
        print(">> ¡Error tipo X aplicado en Qubit 2!")
    elif opcion == '3':
        qubits[2] = 1 - qubits[2]
        print(">> ¡Error tipo X aplicado en Qubit 3!")
    else:
        print(">> El canal no ha introducido errores.")

    print(f"Estado actual (corrupto): |{qubits[0]}{qubits[1]}{qubits[2]}>")

    # 3. MEDICIÓN DE SÍNDROME (MATRIZ H)
    # Calculamos la paridad como explicaste en el trabajo: Z1Z2 y Z2Z3
    # Si son iguales la paridad es 0 (+1), si son distintos es 1 (-1)

    paridad_1_2 = (qubits[0] + qubits[1]) % 2  # Equivalente a medir Z1*Z2
    paridad_2_3 = (qubits[1] + qubits[2]) % 2  # Equivalente a medir Z2*Z3

    print(f"\n3. Medición de Síndromes (Sin mirar los datos):")
    print(f"   Síndrome Z1-Z2: {paridad_1_2}")
    print(f"   Síndrome Z2-Z3: {paridad_2_3}")

    # 4. CORRECCIÓN (TABLA DE LA PÁGINA 9)
    print("\n4. Corrección automática basada en tabla:")

    if paridad_1_2 == 0 and paridad_2_3 == 0:
        print("   -> Síndrome [0,0]: Todo correcto. No se hace nada.")

    elif paridad_1_2 == 1 and paridad_2_3 == 0:
        # Diferencia en el primero par, el segundo bien -> Falló el 1
        print("   -> Síndrome [1,0]: Detectado fallo en Qubit 1.")
        qubits[0] = 1 - qubits[0] # Corregimos
        print("   -> CORRECCIÓN APLICADA.")

    elif paridad_1_2 == 1 and paridad_2_3 == 1:
        # Fallan ambas paridades -> El del medio (2) es el culpable
        print("   -> Síndrome [1,1]: Detectado fallo en Qubit 2.")
        qubits[1] = 1 - qubits[1] # Corregimos
        print("   -> CORRECCIÓN APLICADA.")

    elif paridad_1_2 == 0 and paridad_2_3 == 1:
        # Primer par bien, segundo mal -> Falló el 3
        print("   -> Síndrome [0,1]: Detectado fallo en Qubit 3.")
        qubits[2] = 1 - qubits[2] # Corregimos
        print("   -> CORRECCIÓN APLICADA.")

    print(f"\nESTADO FINAL RECUPERADO: |{qubits[0]}{qubits[1]}{qubits[2]}>")

# Ejecutar simulador
simulador_cuantico_simple()